// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAuthItem = "auth_item"

// AuthItem mapped from table <auth_item>
type AuthItem struct {
	Name        string `gorm:"column:name;primaryKey" json:"name"`
	Type        int16  `gorm:"column:type;not null" json:"type"` // 1 - role, 2 - action
	Parent      string `gorm:"column:parent" json:"parent"`
	Description string `gorm:"column:description" json:"description"`
}

// TableName AuthItem's table name
func (*AuthItem) TableName() string {
	return TableNameAuthItem
}
