// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAuthItemAssignment = "auth_item_assignment"

// AuthItemAssignment mapped from table <auth_item_assignment>
type AuthItemAssignment struct {
	Username string `gorm:"column:username;primaryKey" json:"username"`
	ItemName string `gorm:"column:item_name;primaryKey" json:"item_name"`
}

// TableName AuthItemAssignment's table name
func (*AuthItemAssignment) TableName() string {
	return TableNameAuthItemAssignment
}
