// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSession = "session"

// Session mapped from table <session>
type Session struct {
	ID             string    `gorm:"column:id;primaryKey" json:"id"`
	Key            string    `gorm:"column:key;not null" json:"key"`
	UserID         int32     `gorm:"column:user_id" json:"user_id"`
	CreatedDate    time.Time `gorm:"column:created_date;not null;default:now()" json:"created_date"`
	UpdatedDate    time.Time `gorm:"column:updated_date" json:"updated_date"`
	AllowAutoLogin bool      `gorm:"column:allow_auto_login;not null" json:"allow_auto_login"`
	Data           string    `gorm:"column:data" json:"data"`
	Access         string    `gorm:"column:access" json:"access"`
	IP             string    `gorm:"column:ip;not null" json:"ip"`
	Meta           string    `gorm:"column:meta" json:"meta"`
}

// TableName Session's table name
func (*Session) TableName() string {
	return TableNameSession
}
