// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID            int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name          string    `gorm:"column:name;not null" json:"name"`
	Username      string    `gorm:"column:username;not null" json:"username"`
	Email         string    `gorm:"column:email;not null" json:"email"`
	Password      string    `gorm:"column:password;not null" json:"password"`
	Status        int16     `gorm:"column:status;not null" json:"status"` // 0 - disabled, 5 - waiting confirmation, 10 - active
	CreatedDate   time.Time `gorm:"column:created_date;not null;default:now()" json:"created_date"`
	UpdatedDate   time.Time `gorm:"column:updated_date" json:"updated_date"`
	LastLoginDate time.Time `gorm:"column:last_login_date" json:"last_login_date"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
